# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_chat_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainChatWindow(object):
    def setupUi(self, MainChatWindow):
        MainChatWindow.setObjectName("MainChatWindow")
        MainChatWindow.resize(950, 600)
        MainChatWindow.setStyleSheet("/* ---- Global Styles ---- */\n"
"QDialog#MainChatWindow {\n"
"    background-color: rgb(54, 54, 54);\n"
"}\n"
"\n"
"/* ---- Icon Bar (Far Left) ---- */\n"
"QWidget#iconBar {\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"\n"
"QPushButton#logoutButton {\n"
"    background-color: rgb(54, 54, 54);\n"
"    border: none;\n"
"    padding: 10px;\n"
"    border-radius: 20px; /* Creates a circle for a 40x40 button */\n"
"}\n"
"\n"
"QPushButton#logoutButton:hover {\n"
"    background-color: rgb(220, 80, 80);\n"
"}\n"
"\n"
"/* ---- List Panel (Friends List) ---- */\n"
"QWidget#listPanel {\n"
"    background-color: rgb(48, 48, 48);\n"
"}\n"
"\n"
"QLabel#listPanelTitleLabel {\n"
"    color: white;\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget#friendsListWidget {\n"
"    border: none;\n"
"    color: rgb(200, 200, 200);\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(144, 39, 144);\n"
"    color: white;\n"
"}\n"
"\n"
"/* Style for the addFriendButton (the \'+\') */\n"
"QPushButton#addFriendButton {\n"
"    background-color: rgb(144, 39, 144); /* Reverted to original purple */\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 16pt; /* Adjusted font size for \'+\' */\n"
"    border: none;\n"
"    border-radius: 7px; /* Rounded rectangular shape */\n"
"    padding: 0px; /* Ensure no extra padding, rely on min/max size */\n"
"}\n"
"\n"
"QPushButton#addFriendButton:hover {\n"
"    background-color: rgb(160, 50, 160); /* Slightly brighter purple on hover */\n"
"}\n"
"\n"
"/* ---- Main Chat Area (Right) ---- */\n"
"QLabel#chattingWithLabel {\n"
"    color: white;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QTextEdit#chatDisplay {\n"
"    background-color: rgb(48, 48, 48);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 8px;\n"
"    color: rgb(220, 220, 220);\n"
"    font-size: 11pt;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLineEdit#messageLineEdit {\n"
"    background-color: rgb(48, 48, 48);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 7px;\n"
"    padding: 10px;\n"
"    color: rgb(220, 220, 220);\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QPushButton#sendButton {\n"
"    background-color: rgb(144, 39, 144);\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 7px;\n"
"    padding: 10px 16px;\n"
"}\n"
"\n"
"QPushButton#sendButton:hover {\n"
"    background-color: rgb(160, 50, 160);\n"
"}\n"
"\n"
"QPushButton#sendButton:disabled {\n"
"    background-color: rgb(70, 70, 70);\n"
"    color: rgb(120, 120, 120);\n"
"}\n"
"\n"
"/* ---- Welcome Page Style ---- */\n"
"QLabel#welcomeMessageLabel {\n"
"    font-size: 18pt;\n"
"    font-weight: bold;\n"
"    color: rgb(150, 150, 150);\n"
"}\n"
"\n"
"/* ---- Add Friend Page Styles ---- */\n"
"QLabel#addFriendTitleLabel {\n"
"    color: white;\n"
"    font-size: 18pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit#newFriendUsernameLineEdit {\n"
"    background-color: rgb(48, 48, 48);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 7px;\n"
"    padding: 10px;\n"
"    color: rgb(220, 220, 220);\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QPushButton#sendFriendRequestButton {\n"
"    background-color: rgb(144, 39, 144);\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 7px;\n"
"    padding: 10px 16px;\n"
"}\n"
"\n"
"QPushButton#sendFriendRequestButton:hover {\n"
"    background-color: rgb(160, 50, 160);\n"
"}\n"
"\n"
"QLabel#addFriendStatusLabel {\n"
"    color: rgb(220, 220, 220); /* Default color for status messages */\n"
"}\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainChatWindow)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iconBar = QtWidgets.QWidget(MainChatWindow)
        self.iconBar.setMinimumSize(QtCore.QSize(60, 0))
        self.iconBar.setMaximumSize(QtCore.QSize(60, 16777215))
        self.iconBar.setObjectName("iconBar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.iconBar)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 421, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.logoutButton = QtWidgets.QPushButton(self.iconBar)
        self.logoutButton.setMinimumSize(QtCore.QSize(40, 40))
        self.logoutButton.setMaximumSize(QtCore.QSize(40, 40))
        self.logoutButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutButton.setIcon(icon)
        self.logoutButton.setObjectName("logoutButton")
        self.verticalLayout_3.addWidget(self.logoutButton)
        self.horizontalLayout.addWidget(self.iconBar)
        self.listPanel = QtWidgets.QWidget(MainChatWindow)
        self.listPanel.setMinimumSize(QtCore.QSize(250, 0))
        self.listPanel.setMaximumSize(QtCore.QSize(250, 16777215))
        self.listPanel.setObjectName("listPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.listPanel)
        self.verticalLayout.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listPanelTitleLabel = QtWidgets.QLabel(self.listPanel)
        self.listPanelTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.listPanelTitleLabel.setObjectName("listPanelTitleLabel")
        self.verticalLayout.addWidget(self.listPanelTitleLabel)
        self.friendsListWidget = QtWidgets.QListWidget(self.listPanel)
        self.friendsListWidget.setStyleSheet("background-color:rgb(48, 48, 48);")
        self.friendsListWidget.setObjectName("friendsListWidget")
        self.verticalLayout.addWidget(self.friendsListWidget)
        self.addFriendButton = QtWidgets.QPushButton(self.listPanel)
        self.addFriendButton.setEnabled(True)
        self.addFriendButton.setObjectName("addFriendButton")
        self.verticalLayout.addWidget(self.addFriendButton)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.listPanel)
        self.contentStackedWidget = QtWidgets.QStackedWidget(MainChatWindow)
        self.contentStackedWidget.setObjectName("contentStackedWidget")
        self.welcomePage = QtWidgets.QWidget()
        self.welcomePage.setObjectName("welcomePage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.welcomePage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.welcomeMessageLabel = QtWidgets.QLabel(self.welcomePage)
        self.welcomeMessageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeMessageLabel.setObjectName("welcomeMessageLabel")
        self.verticalLayout_7.addWidget(self.welcomeMessageLabel)
        self.contentStackedWidget.addWidget(self.welcomePage)
        self.chatPage = QtWidgets.QWidget()
        self.chatPage.setObjectName("chatPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.chatPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chattingWithLabel = QtWidgets.QLabel(self.chatPage)
        self.chattingWithLabel.setObjectName("chattingWithLabel")
        self.verticalLayout_2.addWidget(self.chattingWithLabel)
        self.chatDisplay = QtWidgets.QTextEdit(self.chatPage)
        self.chatDisplay.setObjectName("chatDisplay")
        self.verticalLayout_2.addWidget(self.chatDisplay)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.messageLineEdit = QtWidgets.QLineEdit(self.chatPage)
        self.messageLineEdit.setObjectName("messageLineEdit")
        self.horizontalLayout_2.addWidget(self.messageLineEdit)
        self.sendButton = QtWidgets.QPushButton(self.chatPage)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_2.addWidget(self.sendButton)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(1, 1)
        self.contentStackedWidget.addWidget(self.chatPage)
        self.addFriendPage = QtWidgets.QWidget()
        self.addFriendPage.setObjectName("addFriendPage")
        self.verticalLayout_addFriend = QtWidgets.QVBoxLayout(self.addFriendPage)
        self.verticalLayout_addFriend.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout_addFriend.setSpacing(15)
        self.verticalLayout_addFriend.setObjectName("verticalLayout_addFriend")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_addFriend.addItem(spacerItem1)
        self.addFriendTitleLabel = QtWidgets.QLabel(self.addFriendPage)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.addFriendTitleLabel.setFont(font)
        self.addFriendTitleLabel.setStyleSheet("color: white;")
        self.addFriendTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addFriendTitleLabel.setObjectName("addFriendTitleLabel")
        self.verticalLayout_addFriend.addWidget(self.addFriendTitleLabel)
        self.newFriendUsernameLineEdit = QtWidgets.QLineEdit(self.addFriendPage)
        self.newFriendUsernameLineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.newFriendUsernameLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.newFriendUsernameLineEdit.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"border: 1px solid rgb(40, 40, 40);\n"
"border-radius: 7px;\n"
"padding: 10px;\n"
"color: rgb(220, 220, 220);\n"
"font-size: 11pt;")
        self.newFriendUsernameLineEdit.setObjectName("newFriendUsernameLineEdit")
        self.verticalLayout_addFriend.addWidget(self.newFriendUsernameLineEdit)
        self.sendFriendRequestButton = QtWidgets.QPushButton(self.addFriendPage)
        self.sendFriendRequestButton.setMinimumSize(QtCore.QSize(0, 40))
        self.sendFriendRequestButton.setStyleSheet("background-color: rgb(144, 39, 144);\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"border-radius: 7px;\n"
"padding: 10px 16px;")
        self.sendFriendRequestButton.setObjectName("sendFriendRequestButton")
        self.verticalLayout_addFriend.addWidget(self.sendFriendRequestButton)
        self.addFriendStatusLabel = QtWidgets.QLabel(self.addFriendPage)
        self.addFriendStatusLabel.setText("")
        self.addFriendStatusLabel.setStyleSheet("color: rgb(220, 220, 220);")
        self.addFriendStatusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addFriendStatusLabel.setObjectName("addFriendStatusLabel")
        self.verticalLayout_addFriend.addWidget(self.addFriendStatusLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_addFriend.addItem(spacerItem2)
        self.contentStackedWidget.addWidget(self.addFriendPage)
        self.horizontalLayout.addWidget(self.contentStackedWidget)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(MainChatWindow)
        self.contentStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainChatWindow)

    def retranslateUi(self, MainChatWindow):
        _translate = QtCore.QCoreApplication.translate
        MainChatWindow.setWindowTitle(_translate("MainChatWindow", "Secure Chat"))
        self.logoutButton.setToolTip(_translate("MainChatWindow", "Logout"))
        self.listPanelTitleLabel.setText(_translate("MainChatWindow", "Sinyal"))
        self.addFriendButton.setToolTip(_translate("MainChatWindow", "Follow a New User"))
        self.addFriendButton.setText(_translate("MainChatWindow", "+"))
        self.welcomeMessageLabel.setText(_translate("MainChatWindow", "Select a chat to get started"))
        self.chattingWithLabel.setText(_translate("MainChatWindow", "Select a chat to begin"))
        self.messageLineEdit.setPlaceholderText(_translate("MainChatWindow", "Type a message..."))
        self.sendButton.setText(_translate("MainChatWindow", "Send"))
        self.addFriendTitleLabel.setText(_translate("MainChatWindow", "Add New Friend"))
        self.newFriendUsernameLineEdit.setPlaceholderText(_translate("MainChatWindow", "Enter username to add..."))
        self.sendFriendRequestButton.setText(_translate("MainChatWindow", "Send Friend Request"))
